### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by jnsmkl** [naruse/SubTranslate#2]
Any suggestion to this problem? 

admin@hostname:~/.../GitHub/SRTTranslate/sub$ python3 --version
Python 3.5.3

admin@hostname:~/.../GitHub/SRTTranslate/sub$ python3 ../main.py 01.srt en
Translating...
Traceback (most recent call last):
  File "../main.py", line 38, in <module>
    translatedSubInfo = subTranslator.Translate()
  File "/mnt/c/Users/..../GitHub/SRTTranslate/Translator.py", line 24, in Translate
    translatedSubs = self._gs.translate(text, self._translatedLang, self._originalLang)
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 409, in translate
    return _unwrapper_single_element(self._translate_single_text(text, target_language, source_language))
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 334, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 215, in _execute
    raise exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 332, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 251, in _basic_translate
    response_content = self._open_url(url)
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 191, in _open_url
    raise e
  File "/home/admin/.local/lib/python3.5/site-packages/goslate.py", line 181, in _open_url
    response = self._opener.open(request, timeout=self._TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by jnsmkl** [comment]
problem solved 
https://github.com/MarioVilas/googlesearch/issues/75#issuecomment-581319982
